### ISSUE TITLE
Error in UI (refresh fixes)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#1031]
In apache log
```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
[Mon Nov 05 07:40:52.115596 2018] [wsgi:error] [pid 14827:tid 140639822374656]   warnings.warn(warning, RequestsDependencyWarning)
[Mon Nov 05 13:20:40.069359 2018] [wsgi:error] [pid 14827:tid 140639738357504] Internal Server Error: /node/api/v1/dash/info/mysql
[Mon Nov 05 13:20:40.069384 2018] [wsgi:error] [pid 14827:tid 140639738357504] Traceback (most recent call last):
[Mon Nov 05 13:20:40.069387 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
[Mon Nov 05 13:20:40.069390 2018] [wsgi:error] [pid 14827:tid 140639738357504]     response = get_response(request)
[Mon Nov 05 13:20:40.069393 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Mon Nov 05 13:20:40.069396 2018] [wsgi:error] [pid 14827:tid 140639738357504]     response = self._get_response(request)
[Mon Nov 05 13:20:40.069398 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
[Mon Nov 05 13:20:40.069401 2018] [wsgi:error] [pid 14827:tid 140639738357504]     response = self.process_exception_by_middleware(e, request)
[Mon Nov 05 13:20:40.069404 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
[Mon Nov 05 13:20:40.069501 2018] [wsgi:error] [pid 14827:tid 140639738357504]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Mon Nov 05 13:20:40.069507 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
[Mon Nov 05 13:20:40.069509 2018] [wsgi:error] [pid 14827:tid 140639738357504]     return self.dispatch(request, *args, **kwargs)
[Mon Nov 05 13:20:40.069512 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
[Mon Nov 05 13:20:40.069515 2018] [wsgi:error] [pid 14827:tid 140639738357504]     return handler(request, *args, **kwargs)
[Mon Nov 05 13:20:40.069517 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/opt/websafety/var/console/node/views/api_traffic.py", line 45, in get
[Mon Nov 05 13:20:40.069520 2018] [wsgi:error] [pid 14827:tid 140639738357504]     data['stats']['queue'] = FolderInfo(os.path.join(Paths.var_dir(), "monitor")).get_size()
[Mon Nov 05 13:20:40.069522 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/opt/websafety/var/console/_domain/utils/folder.py", line 12, in get_size
[Mon Nov 05 13:20:40.069525 2018] [wsgi:error] [pid 14827:tid 140639738357504]     return self.get_size_internal(self.folder)
[Mon Nov 05 13:20:40.069527 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/opt/websafety/var/console/_domain/utils/folder.py", line 26, in get_size_internal
[Mon Nov 05 13:20:40.069530 2018] [wsgi:error] [pid 14827:tid 140639738357504]     current = self.get_size_internal(newpath)
[Mon Nov 05 13:20:40.069532 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/opt/websafety/var/console/_domain/utils/folder.py", line 18, in get_size_internal
[Mon Nov 05 13:20:40.069589 2018] [wsgi:error] [pid 14827:tid 140639738357504]     return int(os.path.getsize(path))
[Mon Nov 05 13:20:40.069593 2018] [wsgi:error] [pid 14827:tid 140639738357504]   File "/usr/lib/python2.7/genericpath.py", line 57, in getsize
[Mon Nov 05 13:20:40.069595 2018] [wsgi:error] [pid 14827:tid 140639738357504]     return os.stat(filename).st_size
[Mon Nov 05 13:20:40.069598 2018] [wsgi:error] [pid 14827:tid 140639738357504] OSError: [Errno 2] No such file or directory: '/opt/websafety/var/monitor/e3c6c1f1-5970-465f-ba03-49394de7c01e.monitor' 
```

**Comment by ra-at-diladele-com** [comment]
Reason most probably is:

-	Wsicapd daemon writes *.monitor files periodically with traffic monitoring information
-	Each file is processed by wsmgrd daemon and uploaded into UI and then *deleted*
-	UI needs to show the total size of folder taken by the /opt installation and when it calculates the size file gets deleted (see previous)
-	Thus UI throws an error

Ideally we need to catch this error and show “cannot calculate” in UI.

**Comment by ra-at-diladele-com** [comment]
wrapped in try - see if it still works.
