### ISSUE TITLE
UI: FreeBSD / Squid / SSL Filter - the python script to dump certs does not work

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#221]
```
Command /opt/websafety/bin/certmgr.py --action=verify-root-certificate --input=/opt/websafety/etc/myca.pem failed.
	Exit Code: 127
	STDOUT: 
	STDERR: env: python: No such file or directory

Stack:Traceback (most recent call last):
  File "/opt/websafety/var/console/squid/views/ssl.py", line 42, in get_context_data
    cert   = SquidCert().get()
  File "/opt/websafety/var/console/_domain/squid/squid_cert.py", line 141, in get
    return SquidCertDumper().as_json(self.pem_path)
  File "/opt/websafety/var/console/_domain/squid/squid_cert.py", line 42, in as_json
    "Command %s failed.\n\tExit Code: %d\n\tSTDOUT: %s\n\tSTDERR: %s" % (" ".join(args), exit_code, stdout, stderr)
Exception: Command /opt/websafety/bin/certmgr.py --action=verify-root-certificate --input=/opt/websafety/etc/myca.pem failed.
	Exit Code: 127
	STDOUT: 
	STDERR: env: python: No such file or directory
```

**Comment by ra-at-diladele-com** [comment]
When installer builds FreeBSD package it replaces shebang's path to python linux style to one for freebsd

**Comment by ra-at-diladele-com** [comment]
ok seems to work.
