### ISSUE TITLE
CentOS 7 with Squid 4 (cannot upload certificate)

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#924]
Cannot Upload Trusted Root CA Certificate!

Command /usr/bin/sudo /opt/websafety/bin/certmgr.py --action=regenerate-certificate-storage failed. Exit Code: 1 STDOUT: STDERR: Traceback (most recent call last): File "/opt/websafety/bin/certmgr.py", line 547, in <module> main() File "/opt/websafety/bin/certmgr.py", line 542, in main perform_action(args) File "/opt/websafety/bin/certmgr.py", line 461, in perform_action return regenerate_certificate_storage() File "/opt/websafety/bin/certmgr.py", line 181, in regenerate_certificate_storage exe = SslCrtdExe() File "/opt/websafety/bin/certmgr.py", line 109, in __init__ raise Exception("Path to sslcrtd binary does not exist or is not accessible (%s)" % self.exe) Exception: Path to sslcrtd binary does not exist or is not accessible (/usr/lib64/squid/ssl_crtd) Traceback (most recent call last): File "/opt/websafety/var/console/squid/views/ssl.py", line 131, in form_valid cert.upload(data) File "/opt/websafety/var/console/_domain/squid/squid_cert.py", line 188, in upload SquidCertDbInitializer().initialize() File "/opt/websafety/var/console/_domain/squid/squid_cert.py", line 90, in initialize "Command %s failed.\n\tExit Code: %d\n\tSTDOUT: %s\n\tSTDERR: %s" % (" ".join(args), exit_code, stdout, stderr) Exception: Command /usr/bin/sudo /opt/websafety/bin/certmgr.py --action=regenerate-certificate-storage failed. Exit Code: 1 STDOUT: STDERR: Traceback (most recent call last): File "/opt/websafety/bin/certmgr.py", line 547, in <module> main() File "/opt/websafety/bin/certmgr.py", line 542, in main perform_action(args) File "/opt/websafety/bin/certmgr.py", line 461, in perform_action return regenerate_certificate_storage() File "/opt/websafety/bin/certmgr.py", line 181, in regenerate_certificate_storage exe = SslCrtdExe() File "/opt/websafety/bin/certmgr.py", line 109, in __init__ raise Exception("Path to sslcrtd binary does not exist or is not accessible (%s)" % self.exe) Exception: Path to sslcrtd binary does not exist or is not accessible (/usr/lib64/squid/ssl_crtd)

**Comment by ra-at-diladele-com** [comment]
ok fixed
