### ISSUE TITLE
UI / Squid / Auth / Pseudo Auth - Active Directory Inspector does not work

### ISSUE THREAD

**Issue by ra-at-diladele-com** [diladele/websafety-issues#970]
```
Traceback (most recent call last):
  File "/opt/websafety/var/console/squid/views/auth.py", line 915, in get_context_data
    authpseudoad.token).dump()
  File "/opt/websafety/var/console/_domain/squid/pseudo.py", line 45, in dump
    "Command %s failed.\n\tExit Code: %d\n\tSTDOUT: %s\n\tSTDERR: %s" % (" ".join(args), exit_code, stdout, stderr)
Exception: Command /usr/bin/python3 /opt/websafety/bin/inspector_auth.py --server1 dc1.diladele.lan --port1 8443 --dump failed.
	Exit Code: 1
	STDOUT: 
	STDERR: Traceback (most recent call last):
  File "/opt/websafety/bin/inspector_auth.py", line 6, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```

**Comment by ra-at-diladele-com** [comment]
Fixed;
